"""Build karaoke captions — Chinese-aware, optionally bilingual (中英双语).

Chinese scripts: a patched copy of the faceless-explainer captions builder is written to
<project>/.hyperframes/captions-cjk.mjs and run. Patches:
  * break groups at Chinese punctuation as well as ASCII
  * cap a group by character count (≤ --max-chars, punctuation excluded) instead of word count
  * no inter-word spaces; trailing punctuation stripped from the displayed text
  * frame.md's display family + Noto Serif SC as the caption font stack
English scripts (audio_meta.json "language": "en"): the stock builder runs unchanged.

Bilingual (auto when SCRIPT.md has `**EN:**` lines): under each Line's spoken block write
    **EN:** First clause | second clause | third clause
with one English part per Chinese clause (clauses split at ，。？！；：——). Each caption group
then shows its clause's English under the Chinese. A count mismatch falls back to the whole
English line for that frame (with a warning). The English is also stored in caption_groups.json
so reels srt can write bilingual subtitles.

Every patch anchor is asserted — an upstream change fails loudly instead of degrading silently.
Usage: reels captions --project <dir> [--max-chars 16] [--no-bilingual]
"""

import argparse
import json
import re
import subprocess
from pathlib import Path

from reels_rsi.paths import VENDOR as UPSTREAM
CLAUSE_SPLIT = r"[，。？！；：、—…,.?!;:]+"
FACES = (
    "@font-face { font-family: 'Noto Serif SC'; src: url('assets/fonts/NotoSerifSC-Subset.woff2') format('woff2'); font-weight: 200 900; }\\n"
    "  @font-face { font-family: 'Noto Sans SC'; src: url('assets/fonts/NotoSansSC-Subset.woff2') format('woff2'); font-weight: 100 900; }\\n"
)


def display_family(frame_md):
    m = re.search(r"^\s+(?:display|headline):\s*\{[^}]*fontFamily:\s*\"([^\"]+)\"", frame_md, re.M)
    return m.group(1) if m else "Noto Serif SC"


def build_patched(max_chars, family):
    stack = "'Noto Serif SC', serif" if family == "Noto Serif SC" else f"'{family}', 'Noto Serif SC', serif"
    cjk_css = (FACES +
               f"  .caption-line {{ gap: 0.1em 0 !important; letter-spacing: 0.04em !important; font-family: {stack} !important; }}\\n"
               "  .caption-word { padding: 0 0.02em !important; }")
    patches = [
        ('from "./lib/', f'from "{UPSTREAM}/lib/'),
        ("const SENT_END = /[.?!,;:—]$/;", "const SENT_END = /[.?!,;:—，。？！；：、]$/;"),
        ("const r3 = (x) => Number(x.toFixed(3));",
         "const r3 = (x) => Number(x.toFixed(3));\nconst stripPunct = (t) => t.replace(/[，。？！；：、—,.?!;:]+$/u, \"\");"),
        ("const full = cur && cur.words.length >= cur.cap;",
         f"const full = cur && cur.words.reduce((n, x) => n + stripPunct(x.text).length, 0) + stripPunct(w.text).length > {max_chars};"),
        ('text: g.words.map((w) => w.text).join(" "),', 'text: g.words.map((w) => stripPunct(w.text)).join(""),'),
        ("        text: w.text,\n        start: r3(w.start),", "        text: stripPunct(w.text),\n        start: r3(w.start),"),
        ('out += "\\n<style>\\n  .caption-line { line-height: 1.1 !important; }\\n</style>";',
         'out += "\\n<style>\\n  .caption-line { line-height: 1.1 !important; }\\n  ' + cjk_css + '\\n</style>";'),
    ]
    src = (UPSTREAM / "captions.mjs").read_text("utf-8")
    for old, new in patches:
        assert old in src, f"captions.mjs changed upstream — patch anchor not found: {old[:70]!r}"
        src = src.replace(old, new)
    banner = "// GENERATED by reels reels captions — do not edit by hand.\n"
    if src.startswith("#!"):
        first, rest = src.split("\n", 1)
        return first + "\n" + banner + rest
    return banner + src


def parse_en(script):
    """{frame: (spoken_text, [en parts])} from SCRIPT.md `**EN:**` lines."""
    out, frame, spoken = {}, None, ""
    for raw in script.splitlines():
        m = re.match(r"^##\s+Line\s+\d+.*\(Frame\s+(\d+)\)", raw)
        if m:
            frame, spoken = int(m.group(1)), ""
            continue
        if frame is None:
            continue
        m = re.match(r"^(?: {4,}|\t)(.+)$", raw)
        if m:
            spoken += m.group(1).strip()
            continue
        m = re.match(r"^\*\*EN:\*\*\s*(.+)$", raw.strip())
        if m:
            out[frame] = (spoken, [p.strip() for p in m.group(1).split("|") if p.strip()])
    return out


def add_bilingual(project, en_map):
    groups_path = project / "caption_groups.json"
    data = json.loads(groups_path.read_text("utf-8"))
    by_frame = {}
    for g in data["groups"]:
        by_frame.setdefault(g["frame"], []).append(g)
    for frame, groups in by_frame.items():
        if frame not in en_map:
            continue
        spoken, parts = en_map[frame]
        clauses = [c for c in re.split(CLAUSE_SPLIT, spoken) if c]
        whole = " ".join(parts)
        if len(clauses) != len(parts):
            print(f"⚠ frame {frame}: {len(clauses)} Chinese clauses vs {len(parts)} EN parts — showing the whole line")
            for g in groups:
                g["en"] = whole
            continue
        bounds, acc = [], 0
        for c in clauses:
            acc += len(c)
            bounds.append(acc)
        pos = 0
        for g in groups:
            idx = next((i for i, b in enumerate(bounds) if pos < b), len(bounds) - 1)
            g["en"] = parts[idx]
            pos += len(re.sub(CLAUSE_SPLIT, "", g["text"]))
    groups_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), "utf-8")

    html_path = project / "compositions" / "captions.html"
    html = html_path.read_text("utf-8")
    en_by_id = {g["id"]: g.get("en") for g in data["groups"]}
    m = re.search(r"var GROUPS = (\[.*?\]);\n", html)
    assert m, "captions.html: GROUPS literal not found"
    groups_js = json.loads(m.group(1))
    for g in groups_js:
        if en_by_id.get(g.get("id")):
            g["en"] = en_by_id[g["id"]]
    html = html[:m.start(1)] + json.dumps(groups_js, ensure_ascii=False).replace("<", "\\u003c") + html[m.end(1):]
    anchor = "pill.appendChild(line);"
    if anchor not in html:
        print("⚠ caption skin has no `pill.appendChild(line);` anchor — bilingual line skipped")
        html_path.write_text(html, "utf-8")
        return
    html = html.replace(anchor, anchor + '\n      if (group.en) { var en = document.createElement("div"); '
                        'en.className = "caption-en"; en.textContent = group.en; pill.appendChild(en); }', 1)
    css = ("\n<style>\n  .caption-en { font-family: 'Noto Sans SC', sans-serif; font-size: 30px; font-weight: 400; "
           "letter-spacing: 0.01em; line-height: 1.25; margin-top: 8px; text-align: center; "
           "color: color-mix(in srgb, var(--cap-ink, #1b2566) 78%, transparent); }\n</style>\n")
    html = html.replace("</template>", css + "</template>", 1) if html.rstrip().endswith("</template>") else html + css
    html_path.write_text(html, "utf-8")
    n = sum(1 for g in data["groups"] if g.get("en"))
    print(f"✓ bilingual captions: {n}/{len(data['groups'])} groups carry English")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default=".")
    ap.add_argument("--max-chars", type=int, default=16)
    ap.add_argument("--no-bilingual", action="store_true")
    a = ap.parse_args(argv)
    project = Path(a.project).resolve()
    meta = json.loads((project / "audio_meta.json").read_text("utf-8"))
    lang = meta.get("language", "zh")
    args = ["build", "--storyboard", "./STORYBOARD.md", "--audio-meta", "./audio_meta.json",
            "--hyperframes", ".", "--out", "./caption_groups.json"]
    if lang == "en":
        subprocess.run(["node", str(UPSTREAM / "captions.mjs"), *args], cwd=project, check=True)
        # reels presets' skins are tuned for Chinese (no inter-word gap) — restore word spacing
        html_path = project / "compositions" / "captions.html"
        html = html_path.read_text("utf-8")
        css = "\n<style>\n  .caption-line { gap: 0.1em 0.32em !important; letter-spacing: 0 !important; }\n</style>\n"
        html_path.write_text(html.replace("</template>", css + "</template>", 1), "utf-8")
        return
    frame_md = (project / "frame.md").read_text("utf-8") if (project / "frame.md").exists() else ""
    out = project / ".hyperframes" / "captions-cjk.mjs"
    out.parent.mkdir(exist_ok=True)
    out.write_text(build_patched(a.max_chars, display_family(frame_md)), "utf-8")
    subprocess.run(["node", str(out), *args], cwd=project, check=True)
    if not a.no_bilingual:
        en_map = parse_en((project / "SCRIPT.md").read_text("utf-8"))
        if en_map:
            add_bilingual(project, en_map)


if __name__ == "__main__":
    main()
